name: Build micro-ROS Library (Manual Only)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare script
        run: |
          sudo apt-get update
          sudo apt-get install -y dos2unix
          dos2unix extras/library_generation/library_generation.sh
          chmod +x extras/library_generation/library_generation.sh

      - name: Build library
        run: |
          docker run --rm \
            -v $(pwd):/project \
            --env MICROROS_LIBRARY_FOLDER=extras \
            microros/micro_ros_static_library_builder:foxy

      - name: Fix permissions
        run: |
          sudo chown -R $(whoami) .
          sudo chmod -R 755 .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: micro_ros_library
          path: extras