name: Build micro-ROS Library

on:
  workflow_dispatch:   # chỉ chạy khi bạn bấm Run
  push:
    branches:
      - tosy_foxy      # hoặc branch bạn đang dùng

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Fix script (CRLF + permission)
      - name: Prepare script
        run: |
          sudo apt-get update
          sudo apt-get install -y dos2unix
          dos2unix extras/library_generation/library_generation.sh
          chmod +x extras/library_generation/library_generation.sh

      # 3. Build micro-ROS library
      - name: Build library
        run: |
          docker run --rm \
            -v $(pwd):/project \
            --env MICROROS_LIBRARY_FOLDER=extras \
            microros/micro_ros_static_library_builder:foxy

      # 4. Fix quyền file sau khi build
      - name: Fix permissions
        run: |
          sudo chown -R $(whoami) .
          sudo chmod -R 755 .

      # 5. Upload artifact (để download lib về)
      - name: Upload library
        uses: actions/upload-artifact@v4
        with:
          name: micro_ros_library
          path: extras