name: Library generator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  micro_ros_arduino_generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: tosy_foxy

      - name: Get date
        id: date
        run: echo "date=$(date +'%d-%m-%Y %H:%M')" >> $GITHUB_OUTPUT

      - name: Update libraries
        run: |
          docker run --rm -v $(pwd):/project --env MICROROS_LIBRARY_FOLDER=extras microros/micro_ros_static_library_builder:foxy
          sudo chown -R $(whoami) .
          sudo chmod -R 777 .

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: auto update ${{ steps.date.outputs.date }}
          title: auto update ${{ steps.date.outputs.date }}
          branch: autoupdate_tosy_foxy
          delete-branch: true
          base: tosy_foxy